### ISSUE TITLE
Readme file link leads to missing page

### ISSUE THREAD

**Issue by koctbik** [graalvm/mx#132]
Instruction about how to run mx point at
https://wiki.openjdk.java.net/display/Graal/Instructions
which is absent

Would you kindly restore the page or somehow restore the contents.
Also the number of concern line if 19.

**Comment by dougxc** [comment]
I'm fixing it to point to https://github.com/graalvm/graal-core/blob/master/README.md

**Comment by koctbik** [comment]
Ok, thanks whether it is the same as oracle's one.

**Comment by dougxc** [comment]
Fixed in https://github.com/graalvm/mx/commit/4c79e246428c79fdc0bf1a10efca4cfb05086215
