### ISSUE TITLE
Upgrade JaCoCo dependency

### ISSUE THREAD

**Issue by fniephaus** [graalvm/mx#154]
Since [`v0.8.1`](https://github.com/jacoco/jacoco/releases/tag/v0.8.1), JaCoCo supports Java 10 and therefore, it'd be nice if the mx dependency could be updated at some point.

**Comment by dougxc** [comment]
Unfortunately, we've let our usage of JaCoCo fall a bit by the wayside. If you use it via mx, then this would be a great opportunity to add support for `0.8.1` to mx and test it out. Wanna give it a go? ;-)

**Comment by fniephaus** [comment]
As it turned out, our Truffle language has some problems running on JDK10, but runs fine on JDK11. Hopefully, it won't take to long until JaCoCO supports JDK11. But this also means upgrading to 0.8.1 doesn't get us anywhere at the moment. Anyway, I might give this a try when I have a free minute.

**Comment by thiagogcm** [comment]
0.8.2 released with experimental JDK11 support 
https://www.jacoco.org/jacoco/trunk/doc/changes.html

**Comment by fniephaus** [comment]
@thiagogcm thanks for the info. I've opened #159.

**Comment by fniephaus** [comment]
🎉 thanks!

**Comment by christhalinger** [comment]
So close with the hash...
