### ISSUE TITLE
`startswith` matching  of annotated commands limits options for new commands

### ISSUE THREAD

**Issue by zakkak** [graalvm/mx#161]
The following code segment (from https://github.com/graalvm/mx/blob/master/mx.py#L18557):

```
    initial_command = _argParser.initialCommandAndArgs[0] if len(_argParser.initialCommandAndArgs) > 0 else None
    if initial_command and initial_command not in _commands:
        hits = [c for c in _commands.iterkeys() if c.startswith(initial_command)]
        if len(hits) == 1:
            initial_command = hits[0]

    is_suite_context_free = initial_command and initial_command in _suite_context_free
    should_discover_suites = not is_suite_context_free and not (initial_command and initial_command in _no_suite_discovery)
    should_load_suites = should_discover_suites and not (initial_command and initial_command in _no_suite_loading)
    is_optional_suite_context = not initial_command or initial_command in _optional_suite_context

```

forbids the use of commands with names such as `test`, `up`, etc. Actually any command that happens to be a prefix of an annotated built-in command. (and as the number of such commands grows, the restrictions become more and more)

I understand that it is simple to work-around this issue by using a different name for the commands in conflict, but I believe it is better to be less restrictive. Maybe avoiding the `startswith` matching would be enough.

Note: This also breaks backwards compatibility since `mx test` used to work fine before 5.177.1 but breaks with 5.177.1.

**Comment by dougxc** [comment]
This sounds like a reasonable suggestion to me. It does mean that the following commands can no longer be abbreviated on the command line:

annotation | commands
-----------|------------
suite_context_free | init, version, urlrewrite, benchtable, benchplot, sha1, sclone, scloneimports, update
no_suite_discovery | testdownstream, sforceimports
no_suite_loading | pylint, supdate, sbookmarkimports, scheckimports, spull, sincoming, hg_command, stip, sversions
optional_suite_context | help

What do you think @gilles-duboscq ?

**Comment by gilles-duboscq** [comment]
it's a good idea. It might break some scripts though (e.g., `mx sforceimport`).

**Comment by dougxc** [comment]
I think that's only true if the scripts depend on the semantics of the annotation applied to the command. For example, `mx sforceimport` will still correctly invoke the [`sforceimports` command](https://github.com/graalvm/mx/blob/master/mx.py#L16849). It just won't disable suite discovery (i.e. the `@no_suite_discovery` annotation will have effect).

**Comment by zakkak** [comment]
@dougxc I don't see why.

By just removing the following lines:

```
if initial_command and initial_command not in _commands:
        hits = [c for c in _commands.iterkeys() if c.startswith(initial_command)]
        if len(hits) == 1:
            initial_command = hits[0]
```

I would expect everything to be as it is now, except from the abbreviation support (i.e. typing `mx sforcei` instead of `mx sforceimports`). This should be enough to allow the definition of commands that happen to be prefixes of the annotated commands.

**Comment by dougxc** [comment]
I was replying to @gilles-duboscq 's command and saying that I don't think we'll even break existing scripts. There's still abbreviation support [here](https://github.com/graalvm/mx/blob/master/mx.py#L18659-L18666). The only difference is that annotated commands will loose the semantics of their annotations if they are abbreviated.

**Comment by zakkak** [comment]
Oh now I see, I initially misunderstood both comments. Thanks for the clarification.

**Comment by dougxc** [comment]
Should be fixed by https://github.com/graalvm/mx/commit/4fb307edf8a395ff92ad2c57c55d8cd1e10bae9f.

**Comment by zakkak** [comment]
Thanks a lot @dougxc :)
