### ISSUE TITLE
`mx intellijinit` does not work on windows when project dir drive != user's dir drive

### ISSUE THREAD

**Issue by zakkak** [graalvm/mx#175]
Having an mx project in drive "D" and the user's directory in "C" breaks `mx intellijiniit` on windows.

I have traced the issue to be related to the use of `os.path.relpath` in `_intellij_suite`.
mx tries to create relative paths from the project directory to the `.mx` directory which is on a different drive, thus making the creation of a relative path impossible.

**Comment by JornVernee** [comment]
This should have been fixed by https://github.com/graalvm/mx/pull/164

Do you have the latest version of mx?

**Comment by zakkak** [comment]
You are right, I was testing with 5.190.3. Just tried with 5.194.3 and it works. 

Thanks a lot. Both for the contribution as well as for the heads up.
