### ISSUE TITLE
OpenJDK/JDK version string regex not matching for AdoptOpenJDK build

### ISSUE THREAD

**Issue by neomatrix369** [graalvm/mx#198]
The latest changes to `vm/mx.vm/mx_vm.py` gives this error:

```
[snipped]
'/usr/lib/jvm/jdk1.8.0/.' has an unexpected version string:
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.212-b04, mixed mode)
does not match:
(openjdk|java) version \"(?P<jvm_version>[0-9a-z_\-.]+)\".*\n(OpenJDK|Java\(TM\) SE) Runtime Environment( AdoptOpenJDK)? [ 0-9.]*\(build [0-9a-zA-Z_\-.+]+\)
Exited with code 1
```

See https://circleci.com/gh/neomatrix369/awesome-graal/557

Applying this change
https://github.com/neomatrix369/awesome-graal/blob/build-graalvm-suite/build/x86_64/linux_macos/lib/patch/mx_vm.py-VM-version-string-fix.patch, fixes the issue.

I'll create a PR with changes if you agree with the changes - is there a test that checks across multiple JDK versions strings?

**Comment by ansalond** [comment]
Hi @neomatrix369, thanks for the patch. Unfortunately it does not work with AdoptOpenJDK 11:
```
openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.3+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.3+7, mixed mode)
```

We do not have a test that checks across multiple JDKs, but I'm considering replacing these tests with something less problematic and more helpful. I'll keep you updated.

**Comment by ansalond** [comment]
Hi @neomatrix369, can you please check if this fixes your problem?
https://github.com/oracle/graal/commit/10ec24f357950786e1f6754913b0ad0d28efdff9
Thanks!

**Comment by neomatrix369** [comment]
> Hi @neomatrix369, can you please check if this fixes your problem?
> [oracle/graal@10ec24f](https://github.com/oracle/graal/commit/10ec24f357950786e1f6754913b0ad0d28efdff9)
> Thanks!

Thanks for getting back, sorry for the delay in reply, I will take a look at it and report back to you.

**Comment by neomatrix369** [comment]
The fix works good, I'll close the issue
