### ISSUE TITLE
Make mx a python package

### ISSUE THREAD

**Issue by KOLANICH** [graalvm/mx#205]
* [ ] Put all the `*.py` files into an own dir;
* [ ] Rename to remove the prefixes;
* [ ] Figure out the repeating chunks of code, modularize and reuse them
* [ ] Create `setup.cfg` and entry_points in it to use the scripts as CLI tools.
* [ ] create a minimal `setup.py`, it shouldn't contain any metadata

**Comment by sscarduzio** [comment]
no plan to move to Python 3?

**Comment by dougxc** [comment]
Mx already supports python 3. We'd like to remove all python2 support from the code but this is taking a while.
While I would also love to see mx become a proper python package, this is so far down the list of priorities that I fear it will never happen. I'll re-open this issue should we ever find time to do something about it.
