### ISSUE TITLE
Error reading from maven repo

### ISSUE THREAD

**Issue by veganaize** [graalvm/mx#208]
I get this error when trying to build GraalVM 19.3 on a Travis CI Windows Server instance.  However I don't get the error when building on my local Windows dev machine...

`Error reading from https://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)>`

Build details...
https://travis-ci.com/veganaize/graal/builds/142701050#L842

```
  File "C:/Users/travis/mx/mx.py", line 8161, in get_path
    return download_file_with_sha1(self.name, path, urls, self.sha1, sha1path, resolve, not self.optional, canSymlink=not bootClassPathAgent)
  File "C:/Users/travis/mx/mx.py", line 3508, in download_file_with_sha1
    download(cachePath, urls)
```

**Comment by dougxc** [comment]
Maybe the Windows Travis machines are missing some CA certificates?

**Comment by veganaize** [comment]
I am able to download from the same location, via `wget`, on the same Windows Server (Travis CI) instance, without messing with any certificates.  Digging in, it looks like the issue might actually be with Python / `mx`  --which I'd originally thought, but then became almost immediately embarrassed by, for thinking it, in the first place. ☺

So, anyway, the problem seems to be in or around the `download_file_with_sha1` function (`mx.py` Line: 8161).  I've tried updating the Python 2.7.17 certs...  I'm not sure if they actually took or if the cert/keystore is being pulled in from somewhere else.  I've also read that certificates imported with `keytool` (Java) need to be imported in a correct order: https://blogs.oracle.com/jtc/installing-trusted-certificates-into-a-java-keystore

If anyone can shed any light on determining certs / order / etc., especially with regard to `mx` or `maven`, that would be most helpful.
Thank you.

**Comment by dougxc** [comment]
Maybe try using python3 instead of python2?

**Comment by veganaize** [comment]
**Solved**: https://github.com/oracle/graal/issues/1887#issuecomment-573178130
