### ISSUE TITLE
mx requires primary suite to be in a VCS repository

### ISSUE THREAD

**Issue by zakkak** [graalvm/mx#217]
## What happens:

mx fails to build suite when the suite is not in a VCS repository, which is often the case in CI/CD environments that use an archive of the source code instead of cloning the repository. 

## How to reproduce:
```bash
wget https://github.com/oracle/graal/archive/master.zip
unzip master.zip
cd graal-master/compiler
mx help
```

## Current Workaround
```diff
diff --git a/mx.py b/mx.py
index 8cf3518..75aa550 100755
--- a/mx.py
+++ b/mx.py
@@ -1083,7 +1083,7 @@ class SuiteImport:
         if version is None and version_from is None:
             if not (in_subdir and (importer.vc_dir != importer.dir or isinstance(importer, BinarySuite))):
                 abort("In import for '{}': No version given and not a 'subdir' suite of the same repository".format(name), context=context)
-            if importer.isSourceSuite():
+            if importer.isSourceSuite() and importer.vc_dir is not None:
                 suite_dir = join(importer.vc_dir, name)
             version = importer.version()
         if urls is None:
@@ -1490,8 +1490,6 @@ class Suite(object):
     :type dists: list[Distribution]
     """
     def __init__(self, mxDir, primary, internal, importing_suite, load, vc, vc_dir, dynamicallyImported=False):
-        if primary is True and vc_dir is None:
-            abort("The primary suite must be in a vcs repository")
         self.imported_by = [] if primary else [importing_suite]
         self.mxDir = mxDir
         self.dir = dirname(mxDir)
```

Relates to #216

**Comment by gilles-duboscq** [comment]
This is just hiding the problem: for example try building the `graal-nodejs` suite from https://github.com/graalvm/graaljs after taking `graal` and `graaljs` out of their git repo: it will get confused about where to find dependencies and either fail or try to re-clone some of the dependencies.

I don't think this can be solved without at least adding some marker files which tell `mx` where the repo boundaries used to be.

**Comment by zakkak** [comment]
I have toyed a bit with the suggestion about marker files (using `LICENSE` as the marker file) in https://github.com/zakkak/mx/commit/21b8a196eb4b8d43b412b5a3c900a0497fd2e61d and it seems to work.

If you are happy with this let me know so I can open a PR.
I think we should also decide what the marker file should be and possibly make it configurable (e.g. through some environment variable like `MX_MARKER_FILE`)

**Comment by gilles-duboscq** [comment]
> I think we should also decide what the marker file should be and possibly make it configurable (e.g. through some environment variable like `MX_MARKER_FILE`)

What about we use one fixed name that we check into the repos? e.g., `.mx_vcs_root`.

Doing it like this will also require fixing all the code that assume suites have a working VCS both in mx and in exisiting suites.
An alternative is to provide a dummy VCS that works with the marker file. But maybe fixing all the places that assume a working VCS is more future-proof?

**Comment by zakkak** [comment]
> What about we use one fixed name that we check into the repos? e.g., `.mx_vcs_root`.

:+1: I am OK with that

> Doing it like this will also require fixing all the code that assume suites have a working VCS both in mx and in existing suites.

Is there an easy way to find which suites are those?

> An alternative is to provide a dummy VCS that works with the marker file. But maybe fixing all the places that assume a working VCS is more future-proof?

I think I prefer the latter.

**Comment by gilles-duboscq** [comment]
> Is there an easy way to find which suites are those?

Looking for `\.vc(\.|$)` brings up a bunch of interesting matches, a lot in files from mx itself, some in the `sdk`, `substratevm`, and `compiler` suite of the `graal` repo as well as in the `graalpython` repo.
