### ISSUE TITLE
mx fails to pick primary suite if two directories containing graal are present in the same directory

### ISSUE THREAD

**Issue by zakkak** [graalvm/mx#225]
## Issue

mx fails to pick primary suite if two directories containing graal are present in the same directory, e.g.

```
$ tree -L 1
 .
├── graal1
└── graal2
```

## How to reproduce

```
git clone --depth 1 git@github.com:oracle/graal.git graal1
git clone --depth 1 git@github.com:oracle/graal.git graal2
cd graal1
mx --primary-suite substratevm native-image
```

Result:
```
Multiple suites match the import substratevm:
/tmp/graal2/substratevm/mx.substratevm
/tmp/graal1/substratevm/mx.substratevm
```

Same hapens with: `mx --primary-suite-path=./substratevm native-image`

**Comment by zakkak** [comment]
The following patch makes it work, but I am not sure it doesn't break other stuff.

```diff
diff --git a/mx.py b/mx.py
index e76d24b..b4a260b 100755
--- a/mx.py
+++ b/mx.py
@@ -865,14 +865,17 @@ class SuiteModel:
             return None
 
         found = []
-        for dd in os.listdir(searchDir):
-            if suite_import.in_subdir:
-                candidate = join(searchDir, dd, suite_import.name)
-            else:
-                candidate = join(searchDir, dd)
+        if suite_import.in_subdir:
+            candidate = join(searchDir, suite_import.name)
             sd = _is_suite_dir(candidate, _mxDirName(suite_import.name))
             if sd is not None:
                 found.append(sd)
+        else:
+            for dd in os.listdir(searchDir):
+                candidate = join(searchDir, dd)
+                sd = _is_suite_dir(candidate, _mxDirName(suite_import.name))
+                if sd is not None:
+                    found.append(sd)
 
         if len(found) == 0:
             return None
@@ -919,7 +922,7 @@ class SuiteModel:
                 return suite_parent
         else:
             primary_vc_root = suite_dir
-        return dirname(primary_vc_root)
+        return primary_vc_root
 
     @staticmethod
     def _checked_to_importee_tuple(checked, suite_import):
```

**Comment by ansalond** [comment]
Hi @zakkak, thanks for your report and the proposed patch.

Sibling suites are not limited to the vc root of the primary suite, as your proposed changes assume here:
```
    def siblings_dir(suite_dir):
...
-        return dirname(primary_vc_root)
+        return primary_vc_root
```

Example:
```
$ mkdir tmp
$ cd tmp
$ git clone --depth 1 git@github.com:oracle/graal.git
$ git clone --depth 1 git@github.com:graalvm/graaljs.git
$ cd graal
$ mx --primary-suite substratevm --dynamicimports /graal-js graalvm-show
Imported suite 'graal-js' not found (binary or source).
```

We could patch mx to prefer suites that are defined in the primary vc root over suites with the same name that are defined in other vc roots, but it would make things inconsistent and, I believe, more surprising.
For example, from `/vm` you would be able to dynamically import a duplicated `/substratevm` but not a duplicated `/graal-js`.

Instead of changing how suite discovery works, I think I can patch `mx native-image` to avoid calling `mx -p ../vm --dynamicimports /substratevm`. This should not be necessary anymore, and I think it would solve your problem since you probably do not have other dynamic imports.

Would that work for you?

**Comment by zakkak** [comment]
Hi @ansalond 

TBH I would expect `graal` to be under `graaljs` or vice versa (and actually that's what `mx build` in graaljs does if graal is not fount), I personally don't see why it needs to support them as siblings in the same directory (I guess it helps during development though).

> Instead of changing how suite discovery works, I think I can patch `mx native-image` to avoid calling `mx -p ../vm --dynamicimports /substratevm`. This should not be necessary anymore, and I think it would solve your problem since you probably do not have other dynamic imports.
> 
> Would that work for you?

I guess so, at least until I come across another command doing something similar :)

I wonder if we could make `mx` respect `--primary-suite-path` instead. Since the path is absolute or relevant to the directory where `mx` was invoked from there is no ambiguity and I think `mx` should respect that. WDYT?

**Comment by ansalond** [comment]
Sorry for the rather long reply. You are asking interesting and non-trivial questions and I'm trying to be clear about how things work.

> TBH I would expect graal to be under graaljs or vice versa (and actually that's what mx build in graaljs does if graal is not fount)

Please note that `graaljs` does not define an mx suite and you cannot run `mx build` from there:
```
$ mkdir /tmp/tmp_workspace
$ cd /tmp/tmp_workspace
$ git clone --depth 1 git@github.com:graalvm/graaljs.git
$ cd graaljs
$ mx build
no primary suite found for build
```

`graaljs/graal-js` defines an mx suite. If you run `mx build` from there, `graal` gets cloned next to the `graaljs` clone (in `../../graal`). Continuing the previous example:
```
$ cd graal-js
$ mx build
Cloning https://github.com/oracle/graal.git revision 77083ab290a8be68d491aae0921e52ea51576ab0 to /tmp/tmp_workspace/graal with Git
Cloning into '/tmp/tmp_workspace/graal'..
```

>  I personally don't see why it needs to support them as siblings in the same directory 

What I like of the current approach is that I have a single clone, at a predictable location, of each repository I'm interested in. No matter how complex suite hierarchies are, repositories are cloned at the root of the workspace. Then, I can run commands from multiple suites (e.g., `substratevm`, `graal-js`, `graalpython`) and I know that they will use the same version of `compiler`.
We could use git submodules and have suites cloned inside of repositories they depend on, but we decided against it as things would look less intuitive on more complex suite hierarchies, and the downside of having to create a workspace directory is rather minor.

> I guess it helps during development though

Correct, and `mx native-image` is IMO mostly useful for development. For testing, I suggest to clone a specific revision of `graal`, build a GraalVM image containing only what is necessary, and use it to run the tests. Something like this might help:
```
$ cd graal/substratevm
# check what you are about to build
$ mx --components="Native Image" --native-images=native-image graalvm-show
# build it
$ mx --components="Native Image" --native-images=native-image build
# check the location of the newly built GraalVM
$ mx --components="Native Image" --native-images=native-image graalvm-home
```

> I guess so, at least until I come across another command doing something similar :)

Correct, you would have this issue again if you use `--dynamicimports` to import a duplicated suite.

> I wonder if we could make mx respect --primary-suite-path instead. Since the path is absolute or relevant to the directory where mx was invoked from there is no ambiguity and I think mx should respect that. WDYT?

mx respects `--primary-suite-path`, but that option is only for the primary suite. Dynamic imports are handled differently. We could have something like `--dynamicimports ../../graaljs/graal-js`, but I would rather keep enforcing that there are no duplicated suites in the workspace directory.

**Comment by zakkak** [comment]
> Sorry for the rather long reply. You are asking interesting and non-trivial questions and I'm trying to be clear about how things work.
> 

No problem. Thank you for taking the time to reply to these.

> 
> Please note that `graaljs` does not define an mx suite and you cannot run `mx build` from there:
> 
> [snip]
> 
> `graaljs/graal-js` defines an mx suite. If you run `mx build` from there, `graal` gets cloned next to the `graaljs` clone (in `../../graal`). Continuing the previous example:
> 
> ```
> $ cd graal-js
> $ mx build
> Cloning https://github.com/oracle/graal.git revision 77083ab290a8be68d491aae0921e52ea51576ab0 to /tmp/tmp_workspace/graal with Git
> Cloning into '/tmp/tmp_workspace/graal'..
> ```
> 

Ohhh, it looks like I previously used my patched `mx`, which clones graal under graaljs, sorry for that.

> > I personally don't see why it needs to support them as siblings in the same directory
> 
> What I like of the current approach is that I have a single clone, at a predictable location, of each repository I'm interested in. No matter how complex suite hierarchies are, repositories are cloned at the root of the workspace. Then, I can run commands from multiple suites (e.g., `substratevm`, `graal-js`, `graalpython`) and I know that they will use the same version of `compiler`.
> We could use git submodules and have suites cloned inside of repositories they depend on, but we decided against it as things would look less intuitive on more complex suite hierarchies, and the downside of having to create a workspace directory is rather minor.
> 

+1 for avoiding submodules

As you point out the current setup makes it easy to work with multiple suites with complex hierarchies, but makes it hard to work with multiple versions of the same suite in that hierarchy, e.g. trying to see how my branch of a suite behaves in comparison to `master` without having to constantly `git checkout` and possibly rebuild. 

Please note that since I can get away with this (since I am not using such complex hierarchies), and if we avoid the `--dynamicimports` in `mx native-image` I won't even have to create separate workspaces, I am pretty happy with thinks as they are.
Thanks for the replies and for looking into this.

**Comment by ansalond** [comment]
In https://github.com/oracle/graal/commit/716c3a68b04f424929356de323c880c8ec7326b8 I patched `mx native-image` to avoid unnecessary dynamic imports. The general advice is still to avoid duplication of mx suites in the same workspace directory, but your example now works:
{noformat}
$ git clone --depth 1 git@github.com:oracle/graal.git graal1
$ git clone --depth 1 git@github.com:oracle/graal.git graal2
$ cd graal1
$ mx --primary-suite substratevm native-image
{noformat}

Please close this issue if you are ok with this solution.

**Comment by zakkak** [comment]
Great, thanks @ansalond !
