### ISSUE TITLE
Uninformative error when running latest mx build

### ISSUE THREAD

**Issue by davidmrdavid** [graalvm/mx#228]
Hello folks,

I just cloned the latest master from this repo and, after trying to run `mx`, I'm seeing the following exception:

```
Welcome to Mx version 5.273.0
Traceback (most recent call last):
  File "/local/test2/mx/mx.py", line 17008, in <module>
    main()
  File "/local/test2/mx/mx.py", line 16921, in main
    print_simple_help()
  File "/local/test2/mx/mx.py", line 16637, in print_simple_help
    print(ArgumentParser.format_help(_argParser))
  File "/usr/lib/python2.7/argparse.py", line 2314, in format_help
    return formatter.format_help()
  File "/usr/lib/python2.7/argparse.py", line 281, in format_help
    help = self._root_section.format_help()
  File "/usr/lib/python2.7/argparse.py", line 211, in format_help
    func(*args)
  File "/usr/lib/python2.7/argparse.py", line 332, in _format_usage
    assert ' '.join(opt_parts) == opt_usage
AssertionError
```

My JAVA_HOME is pointing to `openjdk1.8.0_242-jvmci-20.0-b02`

My question is: what's wrong and how can I get mx operational again? I want it to build the latest FastR

Thanks!

**Comment by ansalond** [comment]
Hi @davidmrdavid, thanks for your report.

The metavar modified by https://github.com/graalvm/mx/commit/e50f71422a457430443a0a841b410a76799dfd27 introduced a regression on old versions of `argparse`. I don't know which version fixed the issue, but it works with Python 2.7.18 and Python 3.8.5.

If you cannot update your Python version, this should work:
```
diff --git a/mx.py b/mx.py
index e580220..6da7d62 100755
--- a/mx.py
+++ b/mx.py
@@ -520,7 +520,7 @@ environment variables:
         self.add_argument('-y', action='store_const', const='y', dest='answer', help='answer \'y\' to all questions asked')
         self.add_argument('-n', action='store_const', const='n', dest='answer', help='answer \'n\' to all questions asked')
         self.add_argument('-p', '--primary-suite-path', help='set the primary suite directory', metavar='<path>')
-        self.add_argument('--dbg', dest='java_dbg_port', help='make Java processes wait on [<address>:]<port> for a debugger', metavar='[<address>:]<port>')
+        self.add_argument('--dbg', dest='java_dbg_port', help='make Java processes wait on [<address>:]<port> for a debugger', metavar='<address>:<port>')
         self.add_argument('-d', action='store_const', const=8000, dest='java_dbg_port', help='alias for "-dbg 8000"')
         self.add_argument('--attach', dest='attach', help='Connect to existing server running at [<address>:]<port>')
         self.add_argument('--backup-modified', action='store_true', help='backup generated files if they pre-existed and are modified')
```

However, you will probably need Python3 to build FastR:
https://github.com/oracle/fastr/blob/master/documentation/dev/building.md#fastr-specific-requirements

Please close the issue if this works for you.

**Comment by davidmrdavid** [comment]
That works for me, I'll try this later and re-open if it didn't work. thanks!

**Comment by davidmrdavid** [comment]
Just a heads up, I can't seem to get it working with `python 3.8.5`

As per the trace below:
```
root@node:/local/test2# mx
Welcome to Mx version 5.273.2
Traceback (most recent call last):
  File "/local/test2/mx/mx.py", line 17020, in <module>
    main()
  File "/local/test2/mx/mx.py", line 16933, in main
    print_simple_help()
  File "/local/test2/mx/mx.py", line 16638, in print_simple_help
    print(ArgumentParser.format_help(_argParser))
  File "/usr/lib/python2.7/argparse.py", line 2314, in format_help
    return formatter.format_help()
  File "/usr/lib/python2.7/argparse.py", line 281, in format_help
    help = self._root_section.format_help()
  File "/usr/lib/python2.7/argparse.py", line 211, in format_help
    func(*args)
  File "/usr/lib/python2.7/argparse.py", line 332, in _format_usage
    assert ' '.join(opt_parts) == opt_usage
AssertionError
root@node:/local/test2# python
Python 3.8.5 (default, Jul 20 2020, 19:50:14)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

**Comment by davidmrdavid** [comment]
But the fix manual you suggested does work! Feel free to close this issue, I just wanted to communicate that the python upgrade did not fix it :)

**Comment by ansalond** [comment]
I'm sorry, I should have mentioned earlier that the [`mx` script](https://github.com/graalvm/mx/blob/master/mx#L55-L65) by default tries to run `mx.py` on a `python2.7` or a `python2` executable in `$PATH`.

This is why, even if you have a Python 3 `python` executable in `$PATH`, your stack trace shows that you are still running with Python 2.7:
```
  File "/usr/lib/python2.7/argparse.py", line 2314, in format_help
```

Assuming that you also have `python3` in `PATH`, you can:
- set the `MX_PYTHON` environment variable to `python3`:
```
env MX_PYTHON=python3 mx
```
- or set the `MX_PYTHON_VERSION` environment variable to `3`:
```
env MX_PYTHON_VERSION=3 mx
```
- or directly run `mx.py`:
```
$ `which python3` /local/test2/mx/mx.py
```

I'll patch the metavar that causes trouble, but you might still need to run mx with Python 3 to build FastR.

**Comment by ansalond** [comment]
Fixed in https://github.com/graalvm/mx/commit/99a0855b960c3e3fb8d8af0a2f378ebd6598a342.
