### ISSUE TITLE
drop python2 support

### ISSUE THREAD

**Issue by dougxc** [graalvm/mx#249]
Given that Python 2 EOL'ed on 1.1.2020 (https://pythonclock.org/), it's time to drop python2 support from mx.

All major mx suites in the GraalVM project already support python3. Now python2 support just needs to be removed from mx. To maximize availability of Python features for use in mx, the new minimum required python version should be one that has been out for at least a year. According to https://endoflife.date/python, Python 3.9 meets this requirement and gives us about 4 more years before having to worry about EOL issues:

<img width="748" alt="Screen Shot 2021-12-22 at 16 52 32" src="https://user-images.githubusercontent.com/5080087/148466123-864fd20f-46f2-4e11-8185-17db991fab94.png">

Internal tickets: GR-13299, GR-35982

**Comment by zakkak** [comment]
> According to https://endoflife.date/python meets this requirement and gives us about 4 more years before having to worry about EOL issues:
 
I guess you mean "According to https://endoflife.date/python **Python 3.9** meets...", right?

**Comment by zakkak** [comment]
@dougxc we run `mx` in some RHEL 7 systems which [provide Python packages up to 3.8](https://access.redhat.com/documentation/en-us/red_hat_software_collections/3/html/3.8_release_notes/chap-rhscl#sect-RHSCL-Features). As a result, we would like to request the new minimum required python version to be 3.8 instead of 3.9. 

This will still mean ~2.5 years till EOL, and bumping the requirement to 3.9 or a later version in ~2 years shouldn't be as complicated as it is to drop python 2 support.

WDYT?

**Comment by dougxc** [comment]
We've already invested quite some time getting Python 3.9.9 installed and available on all our internal CI machines. Is it not possible to have 3.9 installed on the systems on which you build GraalVM?

**Comment by zakkak** [comment]
> Is it not possible to have 3.9 installed on the systems on which you build GraalVM?

That would require upgrading those systems to RHEL-8. Let me see whether that's possible and what the possible implications of it would be and get back to you.

**Comment by zakkak** [comment]
I confirmed that in case of need it will be possible to upgrade our systems to RHEL-8.
So although we would prefer to stick to python 3.8 and RHEL-7 a work around is possible for when we will need it :)

**Comment by dougxc** [comment]
That's great to hear. I think it's important to buy ourselves as much time as reasonably possible in terms of python version changes so we'll stick with the plan of moving to 3.9 as the minimum.

**Comment by zakkak** [comment]
Hi @dougxc, is there any ETA or update on this?

**Comment by dougxc** [comment]
I plan (hope!) to complete the transition to 3.9 by the end of Feb.

**Comment by dougxc** [comment]
Update: Due to headaches we're still having getting python 3.9 on all our CI machines, we're probably going to drop back to 3.8 as the minimum required version.

**Comment by dougxc** [comment]
This has (finally!) been resolved by 0187b719fbd219fb15ade2cfe84492539b0f57c0
