### ISSUE TITLE
Removed tags from mx repo breaks other tools

### ISSUE THREAD

**Issue by MartinBalin** [graalvm/mx#282]
MX repo has no tags in git as of today. Removing tags breaks other tools like  e.g. NetBeans which has MX project support https://github.com/apache/netbeans/pull/7468#issuecomment-2166392424 
Can you put tags back?
Thank you

**Comment by zakkak** [comment]
+1 This breaks Mandrel CI jobs as well https://github.com/graalvm/mandrel/actions/runs/9508646546/job/26210331455

I guess this was accidental, maybe [a tag rule](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/configuring-tag-protection-rules) could help prevent such issues in the future.

cc @zapster (as the last committer that bumped the mx version)

**Comment by zapster** [comment]
@ezzarghili please have a look

**Comment by ezzarghili** [comment]
There seems to be an issue with the mirroring service pushing tags to github for mx, the team is investigating

**Comment by ezzarghili** [comment]
@fniephaus pushing the missing tags manually for now and I added a rule to look 
[zakkak](https://github.com/zakkak) thanks, I added a rule for now to prevent them from getting deleted

**Comment by fniephaus** [comment]
Apologies for the inconvenience. We've just pushed all `5.*`, `6.*`, and `7.*` tags. Please let me know if something is still missing. As @ezzarghili mentioned, we've set up a tag protection rule to make sure this cannot happen again.

**Comment by MartinBalin** [comment]
Thank you for quick response.

**Comment by zakkak** [comment]
Thank you all for the really fast resolution :)
