### ISSUE TITLE
Pass HTTP_PROXY to maven commands in mx

### ISSUE THREAD

**Issue by chumer** [graalvm/mx#51]
Maven does not respect the HTTP_PROXY environment variable by default. So I think we should pass the proxy directly on each maven call in mx like this.
mvn -DproxySet=true -DproxyHost=myproxy.com -DproxyPort=3128 eclipse:eclipse

**Comment by dougxc** [comment]
Sounds reasonable. @gilles-duboscq can you see any reason not to make this change?

**Comment by gilles-duboscq** [comment]
Sounds good to me. We should just confirm that those arguments really work for maven.

**Comment by dougxc** [comment]
@chumer can you please test the change and create a PR for it.

**Comment by ldaynes** [comment]
can you clarify how one pass the proxy information to mx ? You need to pass both the proxy address and the port number separately right ? Are you planning to have some default mx env variable for indicating those ?

**Comment by gilles-duboscq** [comment]
mx can extract the proxy data from the `http_proxy` environment variable.

**Comment by dougxc** [comment]
We should pull the proxy env var to system property logic from [URLConnectionDownload](https://github.com/graalvm/mx/blob/master/URLConnectionDownload.java#L44) into mx.py to unify this for both maven and URL downloading.

**Comment by dougxc** [comment]
This is fixed by #73.
