### ISSUE TITLE
Support embedded snippets in Truffle

### ISSUE THREAD

**Issue by jtulach** [graalvm/mx#57]
There is a discussion in https://github.com/graalvm/truffle/issues/19 to improve co-location of code snippets to the API that they describe. There are few needed changes in **mx** to make to current proposal functional:
- upgrade to [new version of the doclet](https://github.com/jtulach/codesnippet4javadoc/commit/515fdd141c8caed9d86afce859afb15a81054f7f) (once released)
- add additional parameters to javadoc to specify pattern for files that contain the snippets
-- in *Truffle* they contain letters *Snippets*
- filter out these files from final JARs

Here is the diff that achieves all of that. Can you please tell me how to polish it to be ready for integration into mx repository? Thanks.

```diff
diff --git a/mx.mx/suite.py b/mx.mx/suite.py                                                                                                                                                            
index 679dc5b..b9afd6e 100644                                                                                                                                                                           
--- a/mx.mx/suite.py
+++ b/mx.mx/suite.py
diff --git a/mx.mx/suite.py b/mx.mx/suite.py
index 679dc5b..b9afd6e 100644
--- a/mx.mx/suite.py
+++ b/mx.mx/suite.py
@@ -31,9 +31,9 @@ suite = {
 
     "CODESNIPPET-DOCLET" : {
       "urls" : [
-        "http://repo1.maven.org/maven2/org/apidesign/javadoc/codesnippet-doclet/0.7/codesnippet-doclet-0.7.jar",
+        "file:///home/devel/.m2/repository/org/apidesign/javadoc/codesnippet-doclet/1.0-SNAPSHOT/codesnippet-doclet-1.0-SNAPSHOT.jar",
       ],
-      "sha1" : "28aaf1920d83e1e7d994c50cd23576ef93195434",
+      "sha1" : "fbf655c3f3abdd3d10970f0c5ecf062b6c3c7dc8",
     },
 
     "JUNIT" : {
diff --git a/mx.py b/mx.py
index 9ae0f6b..99fc75c 100755
--- a/mx.py
+++ b/mx.py
@@ -964,6 +964,8 @@ class JARDistribution(Distribution, ClasspathDependency):
                                         services.setdefault(service, []).extend([provider.strip() for provider in fp.readlines()])
                             else:
                                 for f in files:
+                                    if ('Snippets' in f):
+                                        continue
                                     arcname = join(relpath, f).replace(os.sep, '/')
                                     with open(join(root, f), 'rb') as fp:
                                         contents = fp.read()
@@ -10521,6 +10523,7 @@ def javadoc(args, parser=None, docDir='javadoc', includeDeps=True, stdDoclet=Tru
                      '-doclet', 'org.apidesign.javadoc.codesnippet.Doclet',
                      '-docletpath', snippetslib,
                      '-snippetpath', snippets,
+                     '-snippetclasses', '.*Snippets.*',
                      '-source', str(jdk.javaCompliance)] +
                      jdk.javadocLibOptions([]) +
                      ([] if jdk.javaCompliance < JavaCompliance('1.8') else ['-Xdoclint:none']) +
@@ -10617,6 +10620,7 @@ def javadoc(args, parser=None, docDir='javadoc', includeDeps=True, stdDoclet=Tru
              '-doclet', 'org.apidesign.javadoc.codesnippet.Doclet',
              '-docletpath', snippetslib,
              '-snippetpath', snippets,
+             '-snippetclasses', '.*Snippets.*',
              '-sourcepath', sp] +
              ([] if jdk.javaCompliance < JavaCompliance('1.8') else ['-Xdoclint:none']) +
              (['-overview', overviewFile] if exists(overviewFile) else []) +
```

**Comment by woess** [comment]
This filtering based on the class name seems dangerous, and Graal actually has class names with "Snippets" in them.

**Comment by jtulach** [comment]
There are no Snippets classes in Truffle yet, so the pattern is safe for Truffle. But I understand that using such filtering in general may be dangerous. Could the pattern be configurable per suite.py? If so, please hint me how such configuration should look like, thanks.

**Comment by woess** [comment]
I don't like different patterns per suite and would prefer a one-fits-all solution. But maybe a more defensive and specific pattern like `JavadocSnippets` would already do (unlikely to conflict with anything)?

**Comment by rschatz** [comment]
Even if unlikely, it would be very surprising behavior if you accidentially hit it, especially if you don't know about it. Can't we do something with an annotation? E.g. an `@MxDoNotDistribute` annotation on the class? Or perhaps some comment, similar to the already existing `//jacoco exclude`?

**Comment by jtulach** [comment]
Comment is unlikely to work as the JARing operation is performed on .class files, not on sources. Annotation with `Retention.CLASS` might work.

**Comment by jtulach** [comment]
Here is the new diff that introduces *general, one-size-fits-all* solution. It defines new suite tag `snippetsPattern` that is available for any suite using `mx`.

[TruffleAddSinceTag.diff](https://github.com/graalvm/mx/files/155082/TruffleAddSinceTag.txt)

Truffle sets the value to:
```diff
truffle$ git diff
diff --git a/mx.truffle/suite.py b/mx.truffle/suite.py
index ca95e7b..823161f 100644
--- a/mx.truffle/suite.py
+++ b/mx.truffle/suite.py
@@ -39,7 +39,7 @@ suite = {
       }
     },
   },
-
+  "snippetsPattern" : ".*Snippets.*",
   "projects" : {
 
     # ------------- Truffle -------------
```
so the change works nicely with existing changes in https://github.com/jtulach/truffle/commit/14221e4ccdacfeb27f4e836e7243b3f085f9881e - other suites can set the pattern to whatever they want, but most likely they can ignore it, as they don't care that much about API anyway. 

I prefer this regexp based solution to annotations as the doclet is ready for it and it allows us to use one pattern for both associated purposes - the doclet as well as filtering files our of a distribution JAR.

PS: I am waiting for #62 to be accepted. Then I create a pull request to avoid merge conflict.

**Comment by jtulach** [comment]
Let's track the progress in pull request #65
