### ISSUE TITLE
output path of the mx binary distribution jar file is hardcoded to "dists"

### ISSUE THREAD

**Issue by woess** [graalvm/mx#89]
Distribution jar files go into `<output_root>/dists/` (usually `mxbuild/dists/`) but the `<suite>-mx.jar` file is still hardcoded to go into `dists/`. I believe this is a bug and it should go into the same directory as the other jar files.

**Comment by dougxc** [comment]
@woess , do you know if anyone depends on this hard coded path by now?

**Comment by woess** [comment]
@dougxc, not that I know of.

**Comment by dougxc** [comment]
Then can you please create PR for the behavior you request.

**Comment by woess** [comment]
I would expect the jars to go into `join(suite.get_output_root(), 'dists')` but I also see usages in class `BinaryVC` which I'm not sure have to be changed, too.
I don't really care enough about this issue to deal with the intricacies of binary dependencies, so I'll rather close it as wontfix instead.

**Comment by eregon** [comment]
FWIW, what's the `<suite>-mx.jar` jar?

**Comment by mickjordan** [comment]
It's all the suite-specific mx files, e.g. mx_suite.py
